### ISSUE TITLE
Question about the project status

### ISSUE THREAD

**Issue by koalalorenzo** [CloudKarafka/terraform-provider-cloudkarafka#32]
Hello!
I would like to know if this project is actually maintained and/or if there are any plans to have it in the official terraform.
It would even be nice just to have GitHub/GitLab CI/CD to build and release binaries to run tests against Terraform 1.0 :) 

Please let me know as we would love to use this for our infrastructure! <3

**Comment by tbroden84** [comment]
Hi, 

Unfortunately the provider is not current maintained and put on hold. There will be an internal decision made in a couple of weeks, if we can continue with the provider or not.

**Comment by koalalorenzo** [comment]
Please keep us updated! :)

**Comment by tbroden84** [comment]
Will do :)

**Comment by snichme** [comment]
@koalalorenzo better late than never, new version release today and made available on the terraform registry: https://registry.terraform.io/providers/CloudKarafka/cloudkarafka/latest
